name: prep_docker_image

description: Creates a new docker images for PF deployment

inputs:
  USE_CASE_BASE_PATH:
    description: "the flow to be registered and deployed"
    required: true
  DEPLOY_ENVIRONMENT:
    description: "env stage e.g. dev, test, prod"
    required: true



runs:
  using: composite
  steps:
    - name: create docker image
      shell: bash
      run: use_case_base_path=${{ inputs.USE_CASE_BASE_PATH }} deploy_environment=${{ inputs.DEPLOY_ENVIRONMENT }} build_id=${{ github.run_id }} ./llmops/common/scripts/gen_docker_image.sh 